apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: oase
  name: logs-pvc
spec:
  accessModes:
  - ReadWriteMany
  volumeName: logs-pv
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      namespace: oase
      name: logs-pv
  volumeMode: Filesystem