apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: oase
  name: rabbitmq-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  volumeName: rabbitmq-data-pv
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      namespace: oase
      name: rabbitmq-data-pv
  volumeMode: Filesystem