apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: oase
  name: share-pvc
spec:
  accessModes:
  - ReadWriteMany
  volumeName: share-pv
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: oase
      name: share-pv
  volumeMode: Filesystem