version: "3.5"
services:
  oase-web:
    networks:
      - oase-monitoring

  oase-grafana-monitoring:
    image: exastro/oase-grafana-monitoring:${OASE_VERSION:-latest}
    container_name: oase-grafana-monitoring
    hostname: oase-grafana-monitoring
    restart: always
    environment:
      DB_HOST: ${DB_HOST:-mariadb}
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-OASE_DB}
      DB_USER: ${DB_USER:-OASE_USER}
      DB_PASSWORD: ${DB_PASSWORD:-Ch@ngeMe}
      INTERVAL_TIME_GRA_MON: ${INTERVAL_TIME_GRA_MON:-10}
    volumes:
      - ./logs/oase_monitoring:/exastro/OASE/oase-root/logs/backyardlogs/oase_monitoring
    networks:
      - private
      - oase-monitoring

networks:
  oase-monitoring:
    external: true