apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: oase
  name: business-central-data-pv
  labels:
    namespace: oase
    name: business-central-data-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    namespace: oase
    name: business-central-data-pvc
  hostPath:
    path: /tmp/oase/business-central/data
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
