apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: oase
  name: logs-pv
  labels:
    namespace: oase
    name: logs-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    namespace: oase
    name: logs-pvc
  hostPath:
    path: /tmp/oase/logs
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
