apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: oase
  name: share-pv
  labels:
    namespace: oase
    name: share-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    namespace: oase
    name: share-pvc
  hostPath:
    path: /tmp/oase/share
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
