apiVersion: v1
kind: Service
metadata:
  namespace: oase
  name: mariadb
  labels:
    name: mariadb
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 3306
      targetPort: 3306
  selector:
    name: mariadb
