apiVersion: v1
kind: Service
metadata:
  name: oase-web
  namespace: oase
  labels:
    name: oase-web
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - name: service
      port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    name: oase-web
